#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("GladOS.Droid.Resource", IsApplication=true)]

namespace GladOS.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxBind = global::GladOS.Droid.Resource.Attribute.MvxBind;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxDropDownItemTemplate = global::GladOS.Droid.Resource.Attribute.MvxDropDownItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxGroupItemTemplate = global::GladOS.Droid.Resource.Attribute.MvxGroupItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxItemTemplate = global::GladOS.Droid.Resource.Attribute.MvxItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxLang = global::GladOS.Droid.Resource.Attribute.MvxLang;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxSource = global::GladOS.Droid.Resource.Attribute.MvxSource;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxTemplate = global::GladOS.Droid.Resource.Attribute.MvxTemplate;
			global::MvvmCross.Binding.Droid.Resource.Id.MvvmCrossTagId = global::GladOS.Droid.Resource.Id.MvvmCrossTagId;
			global::MvvmCross.Binding.Droid.Resource.Id.MvxBindingTagUnique = global::GladOS.Droid.Resource.Id.MvxBindingTagUnique;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding = global::GladOS.Droid.Resource.Styleable.MvxBinding;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding_MvxBind = global::GladOS.Droid.Resource.Styleable.MvxBinding_MvxBind;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding_MvxLang = global::GladOS.Droid.Resource.Styleable.MvxBinding_MvxLang;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxControl = global::GladOS.Droid.Resource.Styleable.MvxControl;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxControl_MvxTemplate = global::GladOS.Droid.Resource.Styleable.MvxControl_MvxTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxExpandableListView = global::GladOS.Droid.Resource.Styleable.MvxExpandableListView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate = global::GladOS.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxImageView = global::GladOS.Droid.Resource.Styleable.MvxImageView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxImageView_MvxSource = global::GladOS.Droid.Resource.Styleable.MvxImageView_MvxSource;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView = global::GladOS.Droid.Resource.Styleable.MvxListView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate = global::GladOS.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView_MvxItemTemplate = global::GladOS.Droid.Resource.Styleable.MvxListView_MvxItemTemplate;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int MvxBind = 2130771968;
			
			// aapt resource value: 0x7f010004
			public const int MvxDropDownItemTemplate = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int MvxGroupItemTemplate = 2130771973;
			
			// aapt resource value: 0x7f010003
			public const int MvxItemTemplate = 2130771971;
			
			// aapt resource value: 0x7f010001
			public const int MvxLang = 2130771969;
			
			// aapt resource value: 0x7f010006
			public const int MvxSource = 2130771974;
			
			// aapt resource value: 0x7f010002
			public const int MvxTemplate = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int available = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int busy = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int calendar = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int facebook_icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int github_icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Icon = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int linkedin_icon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int meeting = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int office = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int sample_0 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int sample_1 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int sample_2 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int sample_3 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int sample_4 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int sample_5 = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int sample_6 = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int sample_7 = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int schedule = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int splash = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int steve = 2130837523;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int MvvmCrossTagId = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int MvxBindingTagUnique = 2131034113;
			
			// aapt resource value: 0x7f050013
			public const int buttonSave = 2131034131;
			
			// aapt resource value: 0x7f050012
			public const int checkBoxBluetooth = 2131034130;
			
			// aapt resource value: 0x7f050011
			public const int checkBoxGPS = 2131034129;
			
			// aapt resource value: 0x7f05000f
			public const int checkBoxNFC = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int checkBoxWifi = 2131034128;
			
			// aapt resource value: 0x7f050007
			public const int editTextEmail = 2131034119;
			
			// aapt resource value: 0x7f050005
			public const int editTextEmployer = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int editTextName = 2131034116;
			
			// aapt resource value: 0x7f05000d
			public const int editTextPhone = 2131034125;
			
			// aapt resource value: 0x7f050002
			public const int gridLayout1 = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int imageViewDP = 2131034115;
			
			// aapt resource value: 0x7f050008
			public const int imageViewFbIcon = 2131034120;
			
			// aapt resource value: 0x7f05000a
			public const int imageViewGitIcon = 2131034122;
			
			// aapt resource value: 0x7f050009
			public const int imageViewLinkedIcon = 2131034121;
			
			// aapt resource value: 0x7f05000b
			public const int imageViewSchedule = 2131034123;
			
			// aapt resource value: 0x7f050006
			public const int textViewEmail = 2131034118;
			
			// aapt resource value: 0x7f05000e
			public const int textViewLocate = 2131034126;
			
			// aapt resource value: 0x7f05000c
			public const int textViewPhone = 2131034124;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int FirstView = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int FourthView = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int item_person = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int MeetingView = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int SecondView = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int SplashScreen = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int ThirdView = 2130968582;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070001
			public const int ApplicationName = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int Hello = 2131165184;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Theme_Splash = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] MvxBinding = new int[] {
					2130771968,
					2130771969};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			// aapt resource value: 1
			public const int MvxBinding_MvxLang = 1;
			
			public static int[] MvxControl = new int[] {
					2130771970};
			
			// aapt resource value: 0
			public const int MvxControl_MvxTemplate = 0;
			
			public static int[] MvxExpandableListView = new int[] {
					2130771973};
			
			// aapt resource value: 0
			public const int MvxExpandableListView_MvxGroupItemTemplate = 0;
			
			public static int[] MvxImageView = new int[] {
					2130771974};
			
			// aapt resource value: 0
			public const int MvxImageView_MvxSource = 0;
			
			public static int[] MvxListView = new int[] {
					2130771971,
					2130771972};
			
			// aapt resource value: 1
			public const int MvxListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxListView_MvxItemTemplate = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
